### Login -> Done
POST http://127.0.0.1:8000/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "tedx00",
    "password": "aze123200"
}

### User Detials
GET http://127.0.0.1:8000/auth/user/ HTTP/1.1
Authorization: Token 1ce6a1638fca7c95b7d15471a0d30c7a9835a639

### Log out -> Done
POST http://127.0.0.1:8000/auth/logout/ HTTP/1.1

### Registeration -> Done
POST http://127.0.0.1:8000/auth/registration/ HTTP/1.1
Content-Type: application/json

{
    "username":  "tedx00d",
    "password1": "aze123200",
    "password2": "aze123200",
    "email": "tedx.ba0t0nda2.univ@gmail.com"
}

### Verifying Email -> Done
POST http://127.0.0.1:8000/auth/registration/verify-email/ HTTP/1.1
Content-Type: application/json

{
    "key": "NDE:1oXhVs:eRRafCzYdTj6rIw5mjJfCKvkKC-c6YTfS954jwJwOCQ"
}

### Tasks List
GET http://127.0.0.1:8000/api/tasks-list/ HTTP/1.1
Authorization: Token 1ce6a1638fca7c95b7d15471a0d30c7a9835a639

### Change the status of the task
POST http://127.0.0.1:8000/api/change-status/ HTTP/1.1
Content-Type: application/json
Authorization: Token 1ce6a1638fca7c95b7d15471a0d30c7a9835a639

{
    "id": 10
}

### Remove the task
POST http://127.0.0.1:8000/api/remove-task/ HTTP/1.1
Content-Type: application/json
Authorization: Token 1ce6a1638fca7c95b7d15471a0d30c7a9835a639

{
    "id": 7
}

### Remove the task
POST http://127.0.0.1:8000/api/add-task/ HTTP/1.1
Content-Type: application/json
Authorization: Token 1ce6a1638fca7c95b7d15471a0d30c7a9835a639

{
    "task": "hello world from httpssss"
}

### Clear all tasks
POST http://127.0.0.1:8000/api/clear-all-completed-tasks/ HTTP/1.1
Authorization: Token 1ce6a1638fca7c95b7d15471a0d30c7a9835a639
Content-Type: application/json