### Login -> Done
POST http://127.0.0.1:8000/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "aze1232000"
}

### User Detials
GET http://127.0.0.1:8000/auth/user/ HTTP/1.1
Authorization: Token c74fbc4ac61c99ba10d7f3d379fc0a3e332b8d67

### Log out -> Done
POST http://127.0.0.1:8000/auth/logout/ HTTP/1.1

### Registeration -> Doing
POST http://127.0.0.1:8000/auth/registration/ HTTP/1.1
Content-Type: application/json

{
    "username":  "tedx00",
    "password1": "aze123200",
    "password2": "aze123200",
    "email": "tedx.ba0t0na2.univ@gmail.com"
}
### Verifying Email
POST http://127.0.0.1:8000/auth/registration/verify-email/ HTTP/1.1
Content-Type: application/json

{
    "key": "MTc:1oXNlY:vWhEkpbhcdmWUZXAyhuBEgQJOKeI_SGSuvCHIK3szis"
}