# Generated by Django 4.1 on 2022-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=1000),
        ),
    ]
